// <auto-generated />
using System;
using Health_Insurance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Health_Insurance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204205359_addTables")]
    partial class addTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Health_Insurance.Models.AdminLogin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminId");

                    b.ToTable("AdminLogins");
                });

            modelBuilder.Entity("Health_Insurance.Models.CompanyDetails", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyDetails");
                });

            modelBuilder.Entity("Health_Insurance.Models.EmpRegister", b =>
                {
                    b.Property<int>("EmpNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpNo"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("EmpNo");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("EmpRegisters");
                });

            modelBuilder.Entity("Health_Insurance.Models.HospitalInfo", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("HospitalInfos");
                });

            modelBuilder.Entity("Health_Insurance.Models.PoliciesOnEmployees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Emi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<string>("Medical")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("PEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PolicyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PolicyDuration")
                        .HasColumnType("int");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpNo");

                    b.HasIndex("PolicyId");

                    b.ToTable("PoliciesOnEmployees");
                });

            modelBuilder.Entity("Health_Insurance.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Emi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MedicalId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyDesc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PolicyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MedicalId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Health_Insurance.Models.PolicyApprovalDetails", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ApprovalId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RequestId");

                    b.ToTable("PolicyApprovalDetails");
                });

            modelBuilder.Entity("Health_Insurance.Models.PolicyRequestDetails", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AdminRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Emi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("PolicyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.HasIndex("EmpNo");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyRequestDetails");
                });

            modelBuilder.Entity("Health_Insurance.Models.PolicyTotalDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("EMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MedicalId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PolicyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PolicyDesc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PolicyDurationMonths")
                        .HasColumnType("int");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyTotalDescriptions");
                });

            modelBuilder.Entity("Health_Insurance.Models.EmpRegister", b =>
                {
                    b.HasOne("Health_Insurance.Models.CompanyDetails", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Health_Insurance.Models.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId");

                    b.Navigation("Company");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance.Models.PoliciesOnEmployees", b =>
                {
                    b.HasOne("Health_Insurance.Models.EmpRegister", "Employee")
                        .WithMany("PoliciesOnEmployees")
                        .HasForeignKey("EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Health_Insurance.Models.Policy", "Policy")
                        .WithMany("PoliciesOnEmployees")
                        .HasForeignKey("PolicyId");

                    b.Navigation("Employee");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance.Models.Policy", b =>
                {
                    b.HasOne("Health_Insurance.Models.CompanyDetails", "Company")
                        .WithMany("Policies")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Health_Insurance.Models.HospitalInfo", "Medical")
                        .WithMany()
                        .HasForeignKey("MedicalId");

                    b.Navigation("Company");

                    b.Navigation("Medical");
                });

            modelBuilder.Entity("Health_Insurance.Models.PolicyApprovalDetails", b =>
                {
                    b.HasOne("Health_Insurance.Models.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId");

                    b.HasOne("Health_Insurance.Models.PolicyRequestDetails", "PolicyRequest")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.Navigation("Policy");

                    b.Navigation("PolicyRequest");
                });

            modelBuilder.Entity("Health_Insurance.Models.PolicyRequestDetails", b =>
                {
                    b.HasOne("Health_Insurance.Models.EmpRegister", "Employee")
                        .WithMany("PolicyRequests")
                        .HasForeignKey("EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Health_Insurance.Models.Policy", "Policy")
                        .WithMany("PolicyRequests")
                        .HasForeignKey("PolicyId");

                    b.Navigation("Employee");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance.Models.PolicyTotalDescription", b =>
                {
                    b.HasOne("Health_Insurance.Models.Policy", "Policy")
                        .WithMany("PolicyTotals")
                        .HasForeignKey("PolicyId");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Health_Insurance.Models.CompanyDetails", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Health_Insurance.Models.EmpRegister", b =>
                {
                    b.Navigation("PoliciesOnEmployees");

                    b.Navigation("PolicyRequests");
                });

            modelBuilder.Entity("Health_Insurance.Models.Policy", b =>
                {
                    b.Navigation("PoliciesOnEmployees");

                    b.Navigation("PolicyRequests");

                    b.Navigation("PolicyTotals");
                });
#pragma warning restore 612, 618
        }
    }
}
